appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: s2yh8PlcP7S7qgSP1nnGygvwCUbgU8z+m538oy9ma89/NOpawWmJp7x35PAAPbbTzTdUzFuEi8sapiqjruOKRERdS2N6zvMpaoYkwou1dxJMHS4i1FcIOzitoz0P3ZoGhFnqsvfpGC9bL5wdH1KcFuRW9+Y9Cpx4gREfWbUcQbuMO2pfJQepuxdVSulyZ37sxXzdYeyn3aMRQHMtGRAqMN3Oz8yxq0zLPjolrQykS4xJtt2YZ6aDACnST6/nbnZVZ0A+eAP0ChEGojQPQiPOXkwFbR2cYFj4jhM3i3Yeguj0PdJCvhJqCTm1LSjzKcBefwSgQdMSXMXopxUjXFqCnetcaKgWr9m9keb/MaJQu/VuGU5PW/qqpBoI2TsMaGGSIuJSwXRTDwrYaz/ZJMhzigQbIj8JsDWC+mcNCJkbTVEnYjY8tiFJ89IABQ9fmidl6a8lcNUyPAw34Igvr7+mtgCfNbCvNMyqllEOq2XGsj1EaHbtjz3+LZ0WAFJjIQtTYaGfe+Rjr3gZ32mUYeMliKINuZhHkrMAS2FaLxmgeg8lytAuxhbyeW4BdtpPQb6LteXGvre1dMx794NVMedsWiTkyiMSTMJcZ2Q7RmGladMU0T6USGQvN/OROhS9LJCy/D3oGKcRW51LJ1RzqraCkWm4lvvxEksSZMibZdx0tpI=}
bot:
  automerge: true
